### ISSUE TITLE
How to alias table name in TableIdentifier (forces string)

### ISSUE THREAD

**Issue by xorock** [zendframework/zend-db#159]
Before commit https://github.com/zendframework/zend-db/commit/09c67e365177701487a45733a0223fd0c26d3ef3#diff-35f95381c3fd67a5e9b9014a74c266a8 it was allowed to pass array ['t' => 'table'] in constructor ([documentation](https://github.com/zendframework/zend-db/blob/master/doc/book/sql.md) show aliasing as `new TableIdentifier(['t' => 'table'])`). Now constructor allows only string or callable with __toString method.
I see it's very inconsistent. Zend\Db\Sql\Select allows string, array or TableIdentifier. Insert, Update and Delete null|string|TableIdentifier. 
TableGateway -> getTable may return string or TableIdentifier (getTable->getTable chain).
RowGateway is using string or TableIdentifier.

Maybe there should be another class for normalizing this? I'm using postgres with schemas so it's much more noticeable (only TableIdentifier is able to pass schema).

**Comment by alextech** [comment]
Many apologies for delay. I too thought this was a bug and tried to fix until I came across a test case which actually already makes this possible.

https://github.com/zendframework/zend-db/blob/master/test/Sql/SelectTest.php#L807
So the bug is in documentation. Should be `$select->from(['t' => new TableIdentifier('table')]);`, which I fixed in the linked PR.  @xorock please give it a try to see if this fits your usecase.

Your mentioned commit is not faulty because without that restriction `select` specification compiler will crash on table identifier's table property being array. It is being given directly to `quoteIdentifier` not `quoteIdentifierChain` Plus some other aliasing nuances. Having alias part of table identifier is, therefore, not appropriate. I considered adding it either as array like suggested in faulty documentation line, or as third parameter but that takes away from semantic meaning that this object is an identifier of a database object at the database storage level, while alias is something useful only in queries **AND** single table identifier instance can be aliased different ways across multiple queries. 

If we talk about consistence, then I would like to bring up that this is now a third instance of the term `table` in several similar context.

- MetaData table in reverse engineering of schema
- creations and alterations of a table in DDL
- selecting from a table in SQL (here)

There is a lot of redundant concepts between the three use cases.
Maybe in version 3 can have a single `Table` object that can be created, populated from metadata schema, and used as a query data source.
