### ISSUE TITLE
Can't insert row when column name contains dash using PDO

### ISSUE THREAD

**Issue by dkmuir** [zendframework/zend-db#35]
When there's a dash in the column name, inserts and updates fail.
See http://php.net/manual/en/pdo.prepared-statements.php#97162

The relevant code is:
https://github.com/zendframework/zend-db/blob/master/src/Adapter/Driver/Pdo/Pdo.php#L300

Is there a reason why this wouldn't work with positional placeholders instead?

**Comment by alshayed** [comment]
I have a similar issue with my database - we commonly use the pound sign (#) in database field names which doesn't work since PDO only supports alphanumeric and underscore for placeholder/parameter names.

I don't know what downsides there would be to using positional placeholders, but I am working on a patch to filter the parameter names to only allowed characters. I've created a fork and have initial changes but it needs testing.

**Comment by weierophinney** [comment]
Fixed with #224.

**Comment by ezimuel** [comment]
For details, read all the comments of #224.
