### ISSUE TITLE
Test suite issue.

### ISSUE THREAD

**Issue by remicollet** [zendframework/zend-db#97]
Until version 2.7 is was possible to run the test suite (partially) without setting the DB connection parameters.

Since 2.8 this is not possible, if no servers running, the test suite fails.

**Comment by weierophinney** [comment]
@remicollet I did some digging, and the issue is not 2.8.0, but 2.7.1, which introduced a few changes for the pgsql adapter tests. Interestingly, I hadn't noticed them previously, as I was running with a PHP version that did not have ext/pgsql installed; when I switched to one that did, stepping from 2.7.0 to 2.7.1 illustrated the issue.

The changes to Pgsql in 2.7.1 include:

- a change to the default pgsql password in the phpunit.xml.dist file. I tried reverting that, but it had no effect.
- a change to the Pgsql `Connection` class to allow setting the client charset. Reverting that had no effect.

In looking at the errors, it appears that a number of tests are attempting to connect to a pgsql database *when they shouldn't*. One example: `ZendTest\Db\Sql\Ddl\Column\FloatTest::testRaisesDeprecationNoticeOnInstantiation` is triggering a runtime exception during an attempted connection to a pgsql database — but neither the test nor the code it exercises requires an adapter!

I'm going to look into this further later. In the meantime, disable ext/pgsql when attempting to test with no databases; I can vouch that tests run in that situation.

**Comment by remicollet** [comment]
@weierophinney thanks for digging

**Comment by weierophinney** [comment]
Used git bisect to identify the problem commit, and it's c3cc647. Trying to figure out exactly how it affects the test suite still, but at least I know where to look.

**Comment by weierophinney** [comment]
@remicollet Fixed with 2.8.1.

**Comment by remicollet** [comment]
I confirm, issue fixed.
Thanks
